export enum EligibilityCriteria {
	HAS_EXISTING_DIGID = 'HAS_EXISTING_DIGID',
	IS_AGE_18_OR_OLDER = 'IS_AGE_18_OR_OLDER',
	RESIDES_IN_CITY = 'RESIDES_IN_CITY',
	IS_NOT_A_STUDENT = 'IS_NOT_A_STUDENT',
}
