export enum FilterColumnKey {
	CHECKBOX = 'checkboxFilter',
	STATUS = 'statusFilter',
	TITLE = 'titleFilter',
	CITIZEN_OFFER_TYPE = 'citizenOfferTypeFilter',
	OFFER_TYPE = 'offerTypeFilter',
	BENEFITS = 'benefitFilter',
	VALIDITY = 'validityFilter',
	ACTIONS = 'actionsFilter',
	TRANSACTIONS_BENEFIT = 'transactionBenefitFilter',
	TRANSACTIONS_PASSHOLDER_NUMBER = 'passNumberFilter',
	TRANSACTIONS_CITIZEN_NAME = 'citizenNameFilter',
	TRANSACTIONS_SUPPLIER = 'supplierNameFilter',
	TRANSACTIONS_AMOUNT = 'amountFilter',
	TRANSACTIONS_DATE = 'createdDateFilter',
	TRANSACTIONS_TIME = 'createdTimeFilter',
	PASSHOLDERS_NAME = 'nameFilter',
	PASSHOLDERS_BSN = 'bsnFilter',
	PASSHOLDERS_ADDRESS = 'addressFilter',
	PASSHOLDERS_RESIDENCE_CITY = 'residenceCityFilter',
	PASSHOLDERS_EXPIRING_DATE = 'expiringDateFilter',
	PASSHOLDERS_NUMBER = 'passholderNumberFilter',
	PASSHOLDERS_CITIZEN_GROUP = 'citizenGroupNameFilter',
	PASSHOLDERS_REGISTERED = 'isRegisteredFilter',
}
