export enum GeneralInfoFormFields {
	companyName = 'companyName',
	email = 'email',
	ownerName = 'ownerName',
	category = 'category',
	group = 'group',
	subcategory = 'subcategory',
	commerceNumber = 'commerceNumber',
	commerceMainLocation = 'commerceMainLocation',
	commercePostalAdress = 'commercePostalAdress',
	legalform = 'legalForm',
	iban = 'iban',
	bic = 'bic',
	kvkNumber = 'kvkNumber',
	adminEmail = 'adminEmail',
}
