export enum AccountDeletionReason {
  NO_LONGER_USING = "NO_LONGER_USING",
  NOT_USEFUL = "NOT_USEFUL",
  SAFETY_CONCERNS = "SAFETY_CONCERNS",
  PRIVACY_CONCERNS = "PRIVACY_CONCERNS",
  OTHER_REASON = "OTHER_REASON",
}
